---
clickhouse:
  hosts:
    centos7-1:
      ansible_connection: ssh
      ansible_host: 158.160.37.188
      ansible_ssh_user: centos
      ansible_private_key_file: ~/.ssh/id_ed25519
vector:
  hosts:
    centos7-2:
      ansible_connection: ssh
      ansible_host: 158.160.118.189
      ansible_ssh_user: centos
      ansible_private_key_file: ~/.ssh/id_ed25519
lighthouse:
  hosts:
    centos7-3:
      ansible_connection: ssh
      ansible_host: 158.160.115.133
      ansible_ssh_user: centos
      ansible_private_key_file: ~/.ssh/id_ed25519
