{
 "title": "New dashboard Copy",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Disk Free ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(device) (node_filesystem_avail_bytes{fstype!=\"tmpfs\"})"
    }
   ]
  },
  {
   "title": "memory free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job='nodeexporter'}"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}\n"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "утилизация CPU для nodeexporter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100"
    }
   ]
  }
 ]
}